# _config.yml

title: René Koraschnigg
description: Professional portfolio of [René Koraschnigg] – QA Engineer | Automation | CI/CD
theme: minima

# GitHub username for social links or other features
github_username: Reins981

